import psycopg2


create_table_sql = '''
	CREATE TABLE colleges_ca
	(ID		INT		PRIMARY KEY		NOT NULL,
	NAME	TEXT	NOT NULL,
	CITY	TEXT	NOT NULL,
	STATE	TEXT	NOT NULL,
	ZIP		INT		NOT NULL,
	URL		TEXT	NOT NULL,
	ADM_RATE	REAL	NOT NULL,
	SATVR25		INT		NOT NULL,
	SATVR75		INT		NOT NULL,
	SATMT25		INT		NOT NULL,
	SATMT75		INT		NOT NULL,
	SATWR25		INT		NOT NULL,
	SATWR75		INT		NOT NULL,
	SATVRMID	INT		NOT NULL,
	SATMTMID	INT		NOT NULL,
	ACTCM25		INT		NOT NULL,
	ACTCM75		INT		NOT NULL,
	ACTEN25		INT		NOT NULL,
	ACTEN75		INT		NOT NULL,
	ACTMT25		INT		NOT NULL,
	ACTMT75		INT		NOT NULL,
	ACTWR25		INT		NOT NULL,
	ACTWR75		INT		NOT NULL,
	ACTCMMID	INT		NOT NULL,
	ACTENMID	INT		NOT NULL,
	ACTMTMID	INT		NOT NULL,
	ACTWRMID	INT		NOT NULL,
	SAT_AVG		INT		NOT NULL,
	TUITION_IN	INT		NOT NULL,
	TUITION_OUT	INT		NOT NULL
	);
''' 
